version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  translation-api:
    build: ./translation-api
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - MONGO_URL=mongodb://mongo:27017/translationdb
    depends_on:
      - rabbitmq
      - mongo

  translation-worker:
    build: ./translation-worker
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - MONGO_URL=mongodb://mongo:27017/translationdb
    depends_on:
      - rabbitmq
      - mongo

volumes:
  mongo-data:
